networks:
  image-uploader-network:
    driver: bridge

services:
  image-uploader:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: migi987/image-uploader:1.0
    ports:
      - "8080:8080"
    networks:
      - image-uploader-network
    env_file:
      - .env